version: "3"
services:
  myportfolio-load:
    container_name: myportfolio-load
    build: .
    restart: always
    environment:
      - FLASK_ENV=development
      - URL=localhost:3000
      - MYSQL_HOST=mysql-load
      - REDIS_URL=redis://redis-load:6379/0
    env_file:
      - .env
    ports:
      - "3000:5000"
    volumes:
      - .:/myportfolio
    depends_on:
      - mysql-load
      - redis-load
  
  mysql-load:
    container_name: mysql-load
    image: mariadb
    restart: always
    env_file:
      - .env

  redis-load:
    container_name: redis-load
    image: redis:8.2.0-alpine
    restart: always
    ports:
      - "6300:6379"
